# syntax=docker/dockerfile:1.7
ARG SERVING_IMAGE=open-audio-llm/vllm-serving:0.18.0
FROM ${SERVING_IMAGE}

COPY models/qwen3-asr-1.7b /models/qwen3-asr-1.7b

CMD ["-m", "/models/qwen3-asr-1.7b", "-p", "8000", "-n", "Qwen/Qwen3-ASR-1.7B", "-a", "1", "-u", "0.70", "-l", "32768"]
