# syntax=docker/dockerfile:1.7
ARG SERVING_IMAGE=open-audio-llm/vllm-serving:0.18.0
FROM ${SERVING_IMAGE}

ENV OPEN_AUDIO_LLM_ENABLE_LEGACY_AMPHION_ASR=1

COPY models/amphion-spec /models/amphion-spec

CMD ["--config", "examples/configs/serve/amphion-spec.yaml"]
